spring.application.name=auth-service
server.port=8093

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# Exponer endpoints de monitoreo
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# JWT Secret (clave secreta para firmar tokens)
jwt.secret=edwinSecretKey12345
jwt.expiration=3600000  # 1 hora en milisegundos

# H2
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Mostrar SQL en logs
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

## http://localhost:8091/h2-console