spring.application.name=auth-service
server.port=8091

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# JWT Secret (clave secreta para firmar tokens)
jwt.secret=edwinSecretKey12345
jwt.expiration=3600000  # 1 hora en milisegundos
