spring.application.name=api-gateway
server.port=8090

# Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# Exponer endpoints de monitoreo
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Rutas hacia microservicios
spring.cloud.gateway.routes[0].id=email-service
spring.cloud.gateway.routes[0].uri=lb://email-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/email/**

spring.cloud.gateway.routes[1].id=notificacion-service
spring.cloud.gateway.routes[1].uri=lb://notificacion-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/notifications/**
