spring.application.name=notificacion-service
server.port=8092

#Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# Exponer endpoints de monitoreo
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Configuración Circuit Breaker
# Evalúa las últimas 5 llamadas
resilience4j.circuitbreaker.instances.emailService.slidingWindowSize=5
# Si fallan más del 50%, abre el circuito.
resilience4j.circuitbreaker.instances.emailService.failureRateThreshold=50
# Espera 10 segundos antes de volver a intentar.
resilience4j.circuitbreaker.instances.emailService.waitDurationInOpenState=10s

# Configuración Retry
resilience4j.retry.instances.emailService.max-attempts=3
resilience4j.retry.instances.emailService.wait-duration=2s