spring.application.name=notificacion-service
server.port=8092

#Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always